services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petclinic
    ports:
      - "5432:5432"
    volumes:
      - ./.jmix/postgres:/var/lib/postgresql/data